# Generated by Django 4.1 on 2022-08-12 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRMapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leads',
            new_name='Lead',
        ),
    ]
