# Generated by Django 4.1 on 2022-08-17 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRMapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Organisation',
            new_name='Auto',
        ),
    ]
