# Generated by Django 4.1 on 2022-09-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='descripton',
            new_name='description',
        ),
        migrations.AddField(
            model_name='agent',
            name='agent_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
