# Generated by Django 4.1 on 2022-09-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMapp', '0002_rename_descripton_lead_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='agent_details',
        ),
        migrations.AddField(
            model_name='user',
            name='agent_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
