# Generated by Django 4.1 on 2022-08-17 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRMapp', '0002_rename_organisation_auto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='Organisation',
            new_name='organisation',
        ),
    ]
