# Generated by Django 4.1 on 2022-09-24 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRMapp', '0003_remove_agent_agent_details_user_agent_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='agent_details',
        ),
    ]
